import { Wand2 } from "lucide-react";
import { defineForm } from "@/lib/schema";

// Multi-page wizard demo. Demonstrates the dynamic-field binding path:
// - Page 0: static fields only (no n8n data yet)
// - Page 1: a select whose options are injected by n8n via optionsFrom
//
// Expected n8n workflow shape:
// - Page 0 submit POSTs { category } to WEBHOOK_WIZARD_DEMO and returns
//   { options: [{ label, value }, ...] } — the list of available choices
//   for the category-specific field on page 1.
// - Page 1 submit resumes the execution via resumeUrl with { choice }.
export default defineForm({
  slug: "wizard-demo",
  icon: Wand2,
  title: "Wizard Demo",
  description: "Two-page form: page 1 loads its options from n8n at runtime.",
  submitLabel: "Continue",
  successMessage: "All done — n8n processed your selections.",
  pages: [
    {
      // Page 0 — pre-kickoff: static fields only
      title: "Choose a category",
      description: "Your choice determines what options are available on the next page.",
      fields: [
        {
          type: "select",
          name: "category",
          label: "Category",
          required: true,
          options: [
            { label: "Technology", value: "tech" },
            { label: "Design", value: "design" },
            { label: "Business", value: "business" },
          ],
        },
        {
          type: "text",
          name: "context",
          label: "Any context? (optional)",
          placeholder: "e.g. a project name or keyword",
        },
      ],
    },
    {
      // Page 1 — n8n has responded; options come from step data
      title: "Pick a specific option",
      description: "These options were generated by n8n based on your category.",
      retryable: true,
      fields: [
        {
          type: "select",
          name: "choice",
          label: "Your choice",
          required: true,
          // n8n returns { options: [{ label, value }, ...] } in the step data
          optionsFrom: "options",
        },
        {
          type: "textarea",
          name: "notes",
          label: "Notes (optional)",
          placeholder: "Anything else n8n should know…",
        },
      ],
    },
  ],
  response: {
    title: "Result from n8n",
    fields: [
      { key: "category", label: "Category" },
      { key: "choice", label: "Chosen option" },
      { key: "executionId", label: "Execution ID" },
    ],
  },
});
