// @ts-check
// markdown-magic configuration — custom transforms for autogenerated doc sections.
// Syntax: <!-- docs TRANSFORM_NAME [key="value"] --> ... <!-- /docs -->
'use strict'

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse keys from a FIELD_REGISTRY-style TypeScript object literal.
 * Finds `export const <name> ... = { key: Val, ... }` and extracts keys.
 * @param {string} src
 * @param {string} name — e.g. "FIELD_REGISTRY"
 * @returns {string[]}
 */
function parseRegistryKeys(src, name) {
  // Skip the type annotation (no `=`) then find the assignment brace
  const re = new RegExp(`export const ${name}[^=]+=\\s*\\{([^}]+)\\}`, 's')
  const match = src.match(re)
  if (!match) return []
  return [...match[1].matchAll(/^\s{2}(\w+):/gm)].map((m) => m[1])
}

/**
 * Recursively collect files whose name matches `test`, skipping `skip` dirs.
 * Returns paths relative to ROOT.
 * @param {string} dir
 * @param {RegExp} test
 * @param {string[]} [skip]
 * @param {string[]} [results]
 * @returns {string[]}
 */
function collectFiles(dir, test, skip = ['node_modules', '.git', 'dist', 'coverage'], results = []) {
  if (!fs.existsSync(dir)) return results
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name)
    if (entry.isDirectory() && !skip.includes(entry.name)) {
      collectFiles(abs, test, skip, results)
    } else if (entry.isFile() && test.test(entry.name)) {
      results.push(path.relative(ROOT, abs))
    }
  }
  return results
}

// ---------------------------------------------------------------------------
// Transforms
// ---------------------------------------------------------------------------

module.exports = {
  transforms: {
    /**
     * Auto-generate a table of `bun run` commands from package.json scripts.
     * Descriptions come from a `scriptDescriptions` field in package.json.
     *
     * Usage:
     *   <!-- docs PACKAGE_SCRIPTS -->
     *   <!-- /docs -->
     */
    PACKAGE_SCRIPTS(api) {
      const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'))
      const scripts = Object.entries(pkg.scripts ?? {})
      const descriptions = pkg.scriptDescriptions ?? {}

      const rows = scripts.map(([name, cmd]) => {
        const desc = descriptions[name] ?? `\`${cmd}\``
        return `| \`bun run ${name}\` | ${desc} |`
      })

      return ['| Command | Description |', '| --- | --- |', ...rows].join('\n')
    },

    /**
     * Auto-generate field type reference from FIELD_REGISTRY / STATIC_FIELD_REGISTRY.
     * Options:
     *   format="table"  (default) — full markdown table
     *   format="list"             — compact inline lists
     *
     * Usage:
     *   <!-- docs FIELD_TYPES -->
     *   <!-- /docs -->
     *
     *   <!-- docs FIELD_TYPES format="list" -->
     *   <!-- /docs -->
     */
    FIELD_TYPES(api) {
      const source = fs.readFileSync(
        path.join(ROOT, 'src/components/fields/index.ts'),
        'utf8'
      )

      const inputTypes = parseRegistryKeys(source, 'FIELD_REGISTRY')
      const staticTypes = parseRegistryKeys(source, 'STATIC_FIELD_REGISTRY')
      const format = api.options?.format ?? 'table'

      if (format === 'list') {
        return [
          '**Input types** (registered with RHF, contribute to webhook payload):',
          inputTypes.map((t) => `\`${t}\``).join(', '),
          '',
          '**Static display types** (no RHF registration, no payload value — `name` is optional):',
          staticTypes.map((t) => `\`${t}\``).join(', '),
        ].join('\n')
      }

      // table format (default)
      const inputRows = inputTypes.map((t) => {
        const notes =
          t === 'richtext'
            ? 'TipTap editor — sends HTML; debounced ~250 ms, flushes on blur'
            : t === 'select'
              ? 'requires `options: [{label, value}]`'
              : t === 'number'
                ? 'supports `min` / `max`'
                : t === 'rating'
                  ? '`max` defaults to 5, sends number'
                  : t === 'date'
                    ? 'sends ISO date string'
                    : t === 'checkbox'
                      ? 'sends boolean'
                      : ''
        // Empty notes → `| |` (single space); non-empty → `| content |`
        const noteCell = notes ? ` ${notes}` : ''
        return `| \`${t}\` | input |${noteCell} |`
      })
      const staticRows = staticTypes.map(
        (t) => `| \`${t}\` | static | display only — no payload value |`
      )

      return [
        '| `type` | Kind | Notes |',
        '| --- | --- | --- |',
        ...inputRows,
        ...staticRows,
      ].join('\n')
    },

    /**
     * Auto-generate a table of forms discovered in forms/**\/*.form.json5 (and .yaml/.yml).
     * Only includes git-tracked files so private/gitignored forms never appear.
     * Extracts `slug` and `title` from each file via regex.
     *
     * Usage:
     *   <!-- docs FORMS_LIST -->
     *   <!-- /docs -->
     */
    FORMS_LIST(api) {
      const { execSync } = require('child_process')
      const FORM_DATA_RE = /\.form\.(json5|ya?ml)$/
      let formFiles
      try {
        // Only list git-tracked files — gitignored personal forms are excluded automatically
        const out = execSync('git ls-files -- forms/', { cwd: ROOT, encoding: 'utf8' })
        formFiles = out.trim().split('\n').filter((f) => FORM_DATA_RE.test(f))
      } catch {
        // Fallback for non-git environments
        formFiles = collectFiles(path.join(ROOT, 'forms'), FORM_DATA_RE)
      }

      const forms = formFiles
        .map((file) => {
          const src = fs.readFileSync(path.join(ROOT, file), 'utf8')
          const slugM = src.match(/slug:\s*["']([^"']+)["']/)
          const titleM = src.match(/title:\s*["']([^"']+)["']/)
          const slug = slugM?.[1] ?? path.basename(file).replace(FORM_DATA_RE, '')
          const title = titleM?.[1] ?? slug
          return { slug, title, file }
        })
        .sort((a, b) => a.slug.localeCompare(b.slug))

      if (!forms.length) return '_No forms found._'

      const rows = forms.map(
        (f) => `| \`${f.slug}\` | ${f.title} | [\`${f.file}\`](${f.file}) |`
      )
      return ['| Slug | Title | Source |', '| --- | --- | --- |', ...rows].join('\n')
    },
  },
}
